---

- name: Install Zabbix
  package:
    name: [ 'zabbix-server-pgsql', 'zabbix-web-pgsql', 'zabbix-agent' ]
    state: present
  become: true

- name: Init the database
  shell: >
     zcat /usr/share/doc/zabbix-server-pgsql-*/create.sql.gz \
        | psql --dbname='{{ db_conninfo }}'
  register: db_init_out
  changed_when: db_init_out.stderr_lines | length == 0

- name: Fix database connector
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '{{ item.key }}=(.*)'
    line: '{{ item.key }}={{ item.value }}'
    backrefs: true
  no_log: true
  become: true
  loop:
    - { key: 'DBHost',     value: '{{ db_host }}' }
    - { key: 'DBName',     value: '{{ db_name }}' }
    - { key: 'DBUser',     value: '{{ db_user }}' }
    - { key: 'DBPassword', value: '{{ db_pass }}' }

- name: Configure Timezone for Zabbix
  lineinfile:
    path: /etc/httpd/conf.d/zabbix.conf
    line: '        php_value date.timezone America/Los_Angeles'
    insertbefore: '    </IfModule>'
  become: true

- name: Set Admin Password
  command: >
    psql --dbname='{{ db_conninfo }}'
      -c "UPDATE users SET passwd=md5('{{ zb_admin_pass }}') WHERE alias='Admin';"
  # register: a_out
  # changed_when: ???

- name: Configure Web Frontend
  template:
    dest: /etc/zabbix/web/zabbix.conf.php
    src: zabbix.conf.php.j2
  become: true

- name: Add working service file
  template:
    dest: /etc/systemd/system/zabbix-server.service
    src: zabbix-server.service.j2
  become: true
  notify: Reload systemd
  when: false

- meta: flush_handlers

- name: (Re)Start Services
  service:
    name: '{{ item }}'
    state: restarted
    enabled: true
  become: true
  loop:
    - zabbix-server
    - zabbix-agent
    - httpd
