---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: instance
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      - 5432/tcp
      - 80/tcp
    published_ports:
      - 0.0.0.0:5432:5432/tcp
      - 0.0.0.0:80:80/tcp
provisioner:
  name: ansible
  connection_options:
    ansible_connection: docker
  lint:
    name: ansible-lint
    enabled: False
  inventory:
    ansible_connection: docker
verifier:
  name: testinfra
  lint:
    name: flake8
